theme: ./theme

siteConfig:
  title: hhp1614
  description: hhp1614 blog
  url: https://hhp1614.com
  author: hhp1614
  email: hhp1614@gmail.com
  tags:
    - JavaScript
    - CentOS
    - MySQL

themeConfig:
  title: hello, hhp1614
  subTitle: hello world
  copyRight: © hhp1614
  sideBar:
    - text: 主页
      link: /
    - text: 标签
      link: /tags.html
    - text: 关于
      link: /about.html
    - text: 搜索
      link: /so.html

plugins:
  - resolve: saber-plugin-query-posts
    # options:
    #   perPage: 10
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-netlify-redirect
  - resolve: saber-plugin-pwa
  - resolve: saber-plugin-google-analytics
    options:
      trackId: UA-140381390-1
