/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BtnCopy: typeof import('./components/common/BtnCopy.vue')['default']
    BtnIcon: typeof import('./components/common/BtnIcon.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    DatePicker: typeof import('./components/common/DatePicker.vue')['default']
    Dialog: typeof import('./components/common/Dialog.vue')['default']
    Editor: typeof import('./components/common/Editor.vue')['default']
    Footer: typeof import('./components/content/Footer.vue')['default']
    FormCheckbox: typeof import('./components/common/FormCheckbox.vue')['default']
    FormInput: typeof import('./components/common/FormInput.vue')['default']
    FormRadio: typeof import('./components/common/FormRadio.vue')['default']
    FormSelect: typeof import('./components/common/FormSelect.vue')['default']
    Header: typeof import('./components/content/Header.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    Paginate: typeof import('./components/common/Paginate.vue')['default']
    Resize: typeof import('./components/common/Resize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/content/Sidebar.vue')['default']
  }
}
